// The public Nginx configuration limits request bursts. Keep the editable
// browser logic split by responsibility, then ship it as one ordered file so
// a cold page load cannot lose the final runtime script to that limit.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';

const ROOT=path.join(path.dirname(fileURLToPath(import.meta.url)),'..');
const FRONTEND=path.join(ROOT,'frontend');
const LOGIC=['const','i18n','theme','roman','util','design','rank','analysis','data','storage','home','report','comparison','diagnosis','screens','chat','charts','carousel','market','views'];
export const BUNDLE_SOURCES=[...LOGIC.map(name=>`logic/${name}.js`),'app-logic.js','dc-runtime.js'];
export const BUNDLE_PATH=path.join(FRONTEND,'app.bundle.js');

export function buildAssets(){
  const pieces=BUNDLE_SOURCES.map(rel=>{
    const body=fs.readFileSync(path.join(FRONTEND,rel),'utf8').replace(/\s+$/,'');
    return `\n/* source: ${rel} */\n${body}\n`;
  });
  return `/* Generated by scripts/build-assets.mjs. Edit the source files, then run npm run build:html. */\n${pieces.join('')}`;
}

function main(){
  const expected=buildAssets();
  if(process.argv.includes('--check')){
    const current=fs.existsSync(BUNDLE_PATH)?fs.readFileSync(BUNDLE_PATH,'utf8'):'';
    if(current!==expected){console.error('frontend/app.bundle.js 가 원본 스크립트와 다릅니다. `npm run build:html` 을 실행해 주세요.');process.exit(1);}
    console.log('app.bundle.js 가 원본 스크립트와 일치합니다.');return;
  }
  fs.writeFileSync(BUNDLE_PATH,expected);
  console.log(`만들었습니다: frontend/app.bundle.js · 소스 ${BUNDLE_SOURCES.length}개 · ${Buffer.byteLength(expected).toLocaleString()}바이트`);
}

if(process.argv[1]&&import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href)main();
