// The public Nginx configuration limits request bursts. Keep the editable
// browser logic split by responsibility, then ship it as one ordered file so
// a cold page load cannot lose the final runtime script to that limit.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';

const ROOT=path.join(path.dirname(fileURLToPath(import.meta.url)),'..');
const FRONTEND=path.join(ROOT,'frontend');
const LOGIC=['const','i18n','theme','roman','util','design','rank','analysis','data','storage','home','report','comparison','diagnosis','prep','screens','chat','charts','carousel','market','map','views'];
export const BUNDLE_SOURCES=[...LOGIC.map(name=>`logic/${name}.js`),'app-logic.js','dc-runtime.js'];
export const BUNDLE_PATH=path.join(FRONTEND,'app.bundle.js');
export const DATA_BUNDLE_FILES=[
  'data/v3/zone_industry.json','data/v3/sales_by_industry.json','data/v3/stores_by_industry.json',
  'data/v3/zone_gu.json','data/v3/zone_border.json','data/v3/seoul_map.json','data/v3/zone_livepop.json',
  'zone_rent.json','data/v3/rent.json','data/v3/sales_history.json','data/v3/income.json',
  'data/v3/zone_change.json','data/v3/zone_sim.json','data/v3/openings.json',
];
export const DATA_BUNDLE_PATH=path.join(FRONTEND,'data.bundle.js');

export function buildAssets(){
  const pieces=BUNDLE_SOURCES.map(rel=>{
    const body=fs.readFileSync(path.join(FRONTEND,rel),'utf8').replace(/\s+$/,'');
    return `\n/* source: ${rel} */\n${body}\n`;
  });
  return `/* Generated by scripts/build-assets.mjs. Edit the source files, then run npm run build:html. */\n${pieces.join('')}`;
}

export function buildDataBundle(){
  const data=Object.fromEntries(DATA_BUNDLE_FILES.map(rel=>[rel,JSON.parse(fs.readFileSync(path.join(FRONTEND,rel),'utf8'))]));
  const locales=Object.fromEntries(['en','zh-CN'].map(name=>[name,JSON.parse(fs.readFileSync(path.join(FRONTEND,'locales',name+'.json'),'utf8'))]));
  const payload=JSON.stringify({data,locales}).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
  return `/* Generated by scripts/build-assets.mjs. */\nglobalThis.MysbizonBootstrap=Object.freeze(${payload});\n`;
}

function main(){
  const expected=buildAssets(),expectedData=buildDataBundle();
  if(process.argv.includes('--check')){
    const current=fs.existsSync(BUNDLE_PATH)?fs.readFileSync(BUNDLE_PATH,'utf8'):'';
    const currentData=fs.existsSync(DATA_BUNDLE_PATH)?fs.readFileSync(DATA_BUNDLE_PATH,'utf8'):'';
    if(current!==expected||currentData!==expectedData){console.error('생성된 브라우저 파일이 원본과 다릅니다. `npm run build:html` 을 실행해 주세요.');process.exit(1);}
    console.log('app.bundle.js와 data.bundle.js가 원본과 일치합니다.');return;
  }
  fs.writeFileSync(BUNDLE_PATH,expected);
  fs.writeFileSync(DATA_BUNDLE_PATH,expectedData);
  console.log(`만들었습니다: frontend/app.bundle.js · 소스 ${BUNDLE_SOURCES.length}개 · ${Buffer.byteLength(expected).toLocaleString()}바이트`);
  console.log(`만들었습니다: frontend/data.bundle.js · 자료 ${DATA_BUNDLE_FILES.length}개 · ${Buffer.byteLength(expectedData).toLocaleString()}바이트`);
}

if(process.argv[1]&&import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href)main();
